language: c
before_install:
  - sudo pip install cpp-coveralls --use-mirrors
  - sudo pip install rsttst pytest httpie
script:
  - make libuv
  - make libh2o
  - make libck
  - make
  - sudo rsttst README.rst && py.test -vvv
after_success:
  - coveralls --verbose --exclude include --exclude tests --exclude deps
